field_descriptions_pedidos = {
    "AÑO": "Año del pedido u orden de venta.",
    "MES": "Mes del pedido u orden de venta (1 a 12, sin ceros a la izquierda).",
    "MEMO": "Identificador de agrupación de pedidos, especialmente útil para importaciones, ya que un memo puede contener más de un pedido asociado.",
    "PEDIDO": "Número único del pedido u orden de venta.",
    "POSICION_PEDIDO": "Posición específica dentro del pedido. Un pedido puede tener varias posiciones, cada una con su propio material o cantidad.",
    "FECHA_INGRESO_PEDIDO": "Fecha en la que se registró el ingreso del pedido en el sistema.",
    "FECHA_PCP_INICIAL": "Fecha inicial planificada de producción o fabricación del pedido.",
    "FECHA_PCP_REPROGRAMADA": "Fecha reprogramada de producción o fabricación del pedido.",
    "MATERIAL": "Código interno del material o producto solicitado en el pedido.",
    "DESCRIPCION_MATERIAL": "Descripción comercial o técnica del material solicitado en el pedido.",
    "PARTE_CLIENTE": "Identificador o código del material según lo define el cliente. Permite la referencia cruzada entre tu catálogo y el del cliente.",
    "CLIENTE": "Nombre o identificador del cliente que realizó el pedido.",
    "EJECUTIVO_COMERCIAL": "Nombre del ejecutivo comercial responsable de la gestión del pedido.",
    "EJECUTIVO_COMEX": "Nombre del ejecutivo de comercio exterior (Comex) asociado al pedido.",
    "WAREHOUSE": "Nombre del almacén del cliente al que está dirigido el pedido o la orden de venta.",
    "TM_COLOCADO": "Cantidad colocado o colocada del pedido en toneladas métricas (TM), es decir, la cantidad acordada a entregar.",
    "TM_PRODUCCION": "Cantidad del pedido que ya ha sido producida, en toneladas métricas (TM).",
    "TM_DESPACHO": "Cantidad del pedido que ya ha sido despachada o enviada, en toneladas métricas (TM).",
    "TM_FACTURADO": "Cantidad del pedido que ya ha sido facturada al cliente, en toneladas métricas (TM).",
    "DOLARES": "Precio total incluyendo el valor del metal, expresado en dólares estadounidenses (USD).",
    "PREMIO":  "Precio en dolares($) de la tonelada métrica.",
    "PRE": "Es el ingreso en US$, expresado en dólares estadounidenses (USD)."
}